esphome:
  name: floor-heating-sensors
  friendly_name: floor_heating_sensors
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "DXzTVd4qZTXOy+IbZqzcbXXOc59RsvRwZTIVvasA3hc="

ota:
  - platform: esphome
    password: "847a0a6a161e15175ade0affc7b7a31a"
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.4.42
  #manual_ip:
  #  static_ip: 192.168.4.244
  #  gateway: 192.168.4.254
  #  subnet: 255.255.255.0
  #  dns1: 192.168.4.254
  #  dns2: 8.8.8.8 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Floor-Heating-Sensor-1"
    password: "KHgiGGONrx8e"

captive_portal:

one_wire:
    - platform: gpio
      pin: GPIO5
      id: hub_1
    
sensor:
  - platform: dallas_temp
    one_wire_id: hub_1
    address: 0x633cc5f6480dcb28
    name: "Heating first floor in"
    id: fl1_heat_2
    update_interval: 10s

  - platform: dallas_temp
    one_wire_id: hub_1
    address: 0x6a3cd4f648916e28
    name: "Heating first floor out"
    id: "fl1_heat_1"
    update_interval: 10s
    
  - platform: dallas_temp
    one_wire_id: hub_1
    address: 0x823c19f648ad8d28
    name: "Heating second floor in"
    id: fl2_heat_2
    update_interval: 10s

  - platform: dallas_temp
    one_wire_id: hub_1
    address: 0x6b3cfdf6493c5428
    name: "Heating second floor out"
    id: fl2_heat_1
    update_interval: 10s

  
  - platform: template
    name: "Floor1 temp diff"
    id: fl1_temp_diff
    update_interval: 10s
    unit_of_measurement: '°C'
    lambda: !lambda 'return ((id(fl1_heat_2).state)-(id(fl1_heat_1).state));'

  - platform: template
    name: "Floor2 temp diff"
    id: fl2_temp_diff
    update_interval: 10s
    unit_of_measurement: '°C'
    lambda: !lambda 'return ((id(fl2_heat_2).state)-(id(fl2_heat_1).state));'
    
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address 0
      address_1:
        name: ESP IP Address 1
      address_2:
        name: ESP IP Address 2
      address_3:
        name: ESP IP Address 3
      address_4:
        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address
  
web_server:
  port: 80
  version: 1
  ota: False